----------------------------------------------------------------------------
-- IlarosFarm
-- Modul für englische Texte
----------------------------------------------------------------------------

Nodes = {} -- Version enUS und enGB
local region = GetLocale();
if ((region == "enUS") or (region == "enGB")) then
    -- die Namen müssen den tatsächlich im Spiel verwendeten lokalisierten Namen entsprechen, da sie die Suchbegriffe darstellen
    Nodes.Names = {
        -- Bergbau, Erze
        ["Adamantite Deposit"] = 181556,
        ["Cobalt Deposit"] = 189978,
        ["Copper Vein"] = 1731,
        ["Dark Iron Deposit"] = 165658,
        ["Fel Iron Deposit"] = 181555,
        ["Gold Vein"] = 1734,
        ["Goldclover"] = 189973,
        ["Hakkari Thorium Vein"] = 180215,
        ["Incendicite Mineral Vein"] = 1610,
        ["Indurium Mineral Vein"] = 19903,
        ["Iron Deposit"] = 1735,
        ["Khorium Vein"] = 181557,
        ["Lesser Bloodstone Deposit"] = 2653,
        ["Mana Thistle"] = 181281,
        ["Mithril Deposit"] = 2040,
        ["Netherbloom"] = 181279,
        ["Nethercite Deposit"] = 185877,
        ["Netherdust Bush"] = 185881,
        ["Nightmare Vine"] = 181280,
        ["Ooze Covered Gold Vein"] = 73941,
        ["Ooze Covered Mithril Deposit"] = 123310,
        ["Ooze Covered Rich Thorium Vein"] = 177388,
        ["Ooze Covered Silver Vein"] = 73940,
        ["Ooze Covered Thorium Vein"] = 123848,
        ["Ooze Covered Truesilver Deposit"] = 123309,
        ["Rich Adamantite Deposit"] = 181569,
        ["Rich Cobalt Deposit"] = 189979,
        ["Rich Saronite Deposit"] = 189981,
        ["Rich Thorium Vein"] = 175404,
        ["Saronite Deposit"] = 189980,
        ["Silver Vein"] = 1733,
        ["Small Thorium Vein"] = 324,
        ["Tin Vein"] = 1732,
        ["Titanium Vein"] = 191133,
        ["Truesilver Deposit"] = 2047,
        -- Kräuterkunde, Kräuter
        ["Adder's Tongue"] = 191019,
        ["Ancient Lichen"] = 181278,
        ["Arthas' Tears"] = 142141,
        ["Black Lotus"] = 176589,
        ["Blindweed"] = 142143,
        ["Bloodthistle"] = 181166,
        ["Briarthorn"] = 1621,
        ["Bruiseweed"] = 1622,
        ["Dreamfoil"] = 176584,
        ["Dreaming Glory"] = 181271,
        ["Earthroot"] = 1619,
        ["Fadeleaf"] = 2042,
        ["Felweed"] = 181270,
        ["Firebloom"] = 2866,
        ["Firethorn"] = 191303,
        ["Flame Cap"] = 181276,
        ["Frost Lotus"] = 190176,
        ["Frozen Herb"] = 190175,
        ["Ghost Mushroom"] = 142144,
        ["Golden Sansam"] = 176583,
        ["Goldthorn"] = 2046,
        ["Grave Moss"] = 1628,
        ["Gromsblood"] = 142145,
        ["Icecap"] = 176588,
        ["Icethorn"] = 190172,
        ["Khadgar's Whisker"] = 2043,
        ["Kingsblood"] = 1624,
        ["Lichbloom"] = 190171,
        ["Liferoot"] = 2041,
        ["Mageroyal"] = 1620,
        ["Mountain Silversage"] = 176586,
        ["Peacebloom"] = 1618,
        ["Plaguebloom"] = 176587,
        ["Purple Lotus"] = 142140,
        ["Ragveil"] = 181275,
        ["Silverleaf"] = 1617,
        ["Stranglekelp"] = 2045,
        ["Sungrass"] = 142142,
        ["Talandra's Rose"] = 190170,
        ["Terocone"] = 181277,
        ["Tiger Lily"] = 190169,
        ["Wild Steelbloom"] = 1623,
        ["Wintersbite"] = 2044,
        -- Schätze
        ["Adamantite Bound Chest"] = 181802,
        ["Alliance Strongbox"] = 3714,
        ["Armor Crate"] = 3660,
        ["Barrel of Melon Juice"] = 3659,
        ["Barrel of Milk"] = 3705,
        ["Barrel of Sweet Nectar"] = 3706,
        ["Battered Chest"] = 2843,
        ["Battered Footlocker"] = 179486,
        ["Blood of Heroes"] = 176213,
        ["Bloodpetal Sprout"] = 164958,
        ["Blue Power Crystal"] = 164658,
        ["Bound Adamantite Chest"] = 184936,
        ["Bound Fel Iron Chest"] = 184931,
        ["Box of Assorted Parts"] = 19019,
        ["Brightly Colored Egg"] = 113768,
        ["Buccaneer's Strongbox"] = 123330,
        ["Burial Chest"] = 181665,
        ["Cleansed Night Dragon"] = 164881,
        ["Cleansed Songflower"] = 164882,
        ["Cleansed Windblossom"] = 164884,
        ["Cleansed Whipper Root"] = 174622,
        ["Dented Footlocker"] = 179492,
        ["Everfrost Chip"] = 193997,
        ["Fel Iron Chest"] = 181798,
        ["Felsteel Chest"] = 181804,
        ["Food Crate"] = 3662,
        ["Giant Clam"] = 2744,
        ["Glowcap"] = 182053,
        ["Green Power Crystal"] = 164659,
        ["Heavy Fel Iron Chest"] = 181800,
        ["Hidden Strongbox"] = 2039,
        ["Horde Supply Crate"] = 142191,
        ["Large Battered Chest"] = 75293,
        ["Large Darkwood Chest"] = 131979,
        ["Large Iron Bound Chest"] = 74447,
        ["Large Mithril Bound Chest"] = 131978,
        ["Large Solid Chest"] = 74448,
        ["Mossy Footlocker"] = 179493,
        ["Netherwing Egg"] = 185915,
        ["Practice Lockbox"] = 178244,
        ["Primitive Chest"] = 184793,
        ["Red Power Crystal"] = 164660,
        ["Scarlet Footlocker"] = 179498,
        ["Scattered Crate"] = 28604,
        ["Shellfish Trap"] = 176582,
        ["Solid Chest"] = 2850,
        ["Solid Fel Iron Chest"] = 184930,
        ["Tattered Chest"] = 2844,
        ["Un'Goro Dirt Pile"] = 157936,
        ["Water Barrel"] = 3658,
        ["Waterlogged Footlocker"] = 179487,
        ["Weapon Crate"] = 3661,
        ["Yellow Power Crystal"] = 164661,
        ["Wicker Chest"] = 184740,
        -- Fische
        ["Baby Crocolisk"] = 534864,
        ["Barbed Gill Trout"] = 527422,
        ["Blackfin Darter"] = 534856,
        ["Bloated Barbed Gill Trout"] = 535313,
        ["Borean Man O' War"] = 541805,
        ["Darkclaw Lobster"] = 513888,
        ["Deep Sea Monsterbelly"] = 541800,
        ["Deviate Fish"] = 506522,
        ["Dragonfin Angelfish"] = 541807,
        ["Fangtooth Herring"] = 541810,
        ["Figluster's Mudfish"] = 527435,
        ["Firefin Snapper"] = 506359,
        ["Furious Crawdad"] = 527439,
        ["Glacial Salmon"] = 541809,
        ["Glassfin Minnow"] = 541814,
        ["Golden Darter"] = 527438,
        ["Icefin Bluefish"] = 527437,
        ["Imperial Manta Ray"] = 541802,
        ["Large Raw Mightfish"] = 513893,
        ["Monstrous Felblood Snapper"] = 534867,
        ["Moonglow Cuttlefish"] = 541801,
        ["Musselback Sculpin"] = 541806,
        ["Nettlefish"] = 541813,
        ["Oily Blackmouth"] = 506358,
        ["Raw Brilliant Smallfish"] = 506291,
        ["Raw Greater Sagefish"] = 521153,
        ["Raw Longjaw Mud Snapper"] = 506289,
        ["Raw Mithril Head Trout"] = 508365,
        ["Raw Nightfin Snapper"] = 513759,
        ["Raw Redgill"] = 513758,
        ["Raw Sagefish"] = 521071,
        ["Raw Summer Bass"] = 513756,
        ["Raw Sunscale Salmon"] = 513760,
        ["Speckled Tastyfish"] = 519807,
        ["Spotted Feltail"] = 527425,
        ["Stonescale Eel"] = 513422,
        ["World's Largest Mudfish"] = 534868,
        ["Zangarian Sporefish"] = 527429,
        ["Zulian Mudskunk"] = 519975,
        ["Elemental Water"] = 507070,
        ["Iron Bound Trunk"] = 521150,
        ["Mithril Bound Trunk"] = 521228,
        ["Mote of Water"] = 522578,
        ["Rumsey Rum Black Label"] = 521151,
        ["Steam Pump Debris"] = 527443,
        ["Tightly Sealed Trunk"] = 520708,
        ["Watertight Trunk"] = 521113,
        -- Fischschwärme
        ["Bluefish School"] = 182959,
        ["Borean Man O' War School"] = 192051,
        ["Brackish Mixed School"] = 182954,
        ["Deep Sea Monsterbelly School"] = 192053,
        ["Dragonfin Angelfish School"] = 192048,
        ["Fangtooth Herring School"] = 192049,
        ["Firefin Snapper School"] = 180683, -- auch
        -- ["Sparse Firefin Snapper School"] = 180657,
        -- ["Abundant Firefin Snapper School"] = 180902,
        -- ["Teeming Firefin Snapper School"] = 180752,
        -- ["Oil Spill"] = 180661,
        ["Glacial Salmon School"] = 192050,
        ["Glassfin Minnow School"] = 192059,
        ["Greater Sagefish School"] = 180684, -- auch
        --  ["Strange Pool"] = 184845, 184956
        ["Highland Mixed School"] = 182957,
        ["Imperial Manta Ray School"] = 192052,
        ["Moonglow Cuttlefish School"] = 192054,
        ["Muddy Churning Waters"] = 180369,
        ["Mudfish School"] = 182958,
        ["Musselback Sculpin School"] = 192046,
        ["Nettlefish School"] = 192057,
        ["Oily Blackmouth School"] = 180682, -- auch
        -- ["Sparse Oily Blackmouth School"] = 180664,
        -- ["Lesser Oily Blackmouth School"] = 180582,
        -- ["Abundant Oily Blackmouth School"] = 180900,
        -- ["Teeming Oily Blackmouth School"] = 180750,
        ["Sagefish School"] = 180663, -- auch
        -- ["Lesser Sagefish School"] = 180656,
        ["School of Darter"] = 182956,
        ["School of Deviate Fish"] = 180658,
        ["School of Tastyfish"] = 180248,
        ["Sporefish School"] = 182953,
        ["Stonescale Eel Swarm"] = 180712,
        ["Bloodsail Wreckage"] = 180901,
        ["Floating Debris"] = 180655,
        ["Floating Wreckage"] = 180751,
        ["Patch of Elemental Water"] = 180753,
        ["Pure Water"] = 182951,
        ["Schooner Wreckage"] = 180662,
        ["Steam Pump Flotsam"] = 182952,
        ["Waterlogged Wreckage"] = 180685,
    }

    -- Fertigkeiten
    FarmText_SKL = {
        ["HERB"] = "Herbalism",
        ["MINE"] = "Mining",
        ["FISH"] = "Fishing",
        ["OPEN"] = "Treasure",
    }

    -- lokalisierte ObjectCategoryNames, die nicht mit IlarosFarm.Node.Names identisch sind (wozu?)
    FarmText_HERB_NETHERDUST = "Netherdust Pollen"
    FarmText_ORE_ADAMANTITE  = "Adamantite"
    FarmText_ORE_BLOODSTONE  = "Lesser Bloodstone"
    FarmText_ORE_COPPER  = "Copper"
    FarmText_ORE_DARKIRON    = "Dark Iron"
    FarmText_ORE_FELIRON = "Fel Iron"
    FarmText_ORE_GOLD    = "Gold"
    FarmText_ORE_INCENDICITE = "Incendicite"
    FarmText_ORE_INDURIUM    = "Indurium"
    FarmText_ORE_IRON    = "Iron"
    FarmText_ORE_KHORIUM = "Khorium"
    FarmText_ORE_MITHRIL = "Mithril"
    FarmText_ORE_NETHERCITE  = "Nethercite"
    FarmText_ORE_OBSIDIAN    = "Obsidian"
    FarmText_ORE_RADAMANTITE = "Rich Adamantite"
    FarmText_ORE_RTHORIUM    = "Rich Thorium"
    FarmText_ORE_SILVER  = "Silver"
    FarmText_ORE_THORIUM = "Thorium"
    FarmText_ORE_TIN = "Tin"
    FarmText_ORE_TRUESILVER  = "Truesilver"
    FarmText_TREASURE_BARREL = "Barrels"
    FarmText_TREASURE_BLOODPETAL = "Bloodpetal Sprouts"
    FarmText_TREASURE_BOX    = "Boxes"
    FarmText_TREASURE_CASK   = "Casks"
    FarmText_TREASURE_CHEST  = "Treasure Chests"
    FarmText_TREASURE_CLAM   = "Giant Clams"
    FarmText_TREASURE_CRATE  = "Crates"
    FarmText_TREASURE_FOOTLOCKER = "Footlockers"
    FarmText_TREASURE_GLOWCAP    = "Glowcaps"
    FarmText_TREASURE_NIGHTDRAGON    = "Night Dragon's Breath"
    FarmText_TREASURE_POWERCRYST = "Power Crystals"
    FarmText_TREASURE_SHELLFISHTRAP  = "Shellfish Traps"
    FarmText_TREASURE_SONGFLOWER = "Songflowers"
    FarmText_TREASURE_UNGOROSOIL = "Un'Goro Soil"
    FarmText_TREASURE_WHIPPERROOT    = "Whipper Root Tubers"
    FarmText_TREASURE_WINDBLOSSOM    = "Windblossom Berries"
    FarmText_FISH_GLASSFINMINNOW = "Glassfin Minnows"

    -- Tooltips
    FarmText_TT1 = "%d additionally found"
    FarmText_TT2 = "Farmed: %d"
    FarmText_TT3 = "Distance: %0.2f yards"
    FarmText_TT4 = "Last visited: %s"
    FarmText_TT5 = "Average drop rates:"
    FarmText_TT6 = "Source: %s"
    FarmText_TT7 = "Imported"
    FarmText_TT8 = "Unsufficient skill"

    -- Zeitangaben
    FarmText_TStrS1 = "Sec."
    FarmText_TStrS2 = "Secs."
    FarmText_TStrM1 = "Min."
    FarmText_TStrM2 = "Mins."
    FarmText_TStrH1 = "Hr."
    FarmText_TStrH2 = "Hrs."
    FarmText_TStrD1 = "Day"
    FarmText_TStrD2 = "Days"
    FarmText_TStrW1 = "Wk."
    FarmText_TStrW2 = "Wks."

    -- Konfigurationsfenster
    FarmText_CNF1 = "Tracking"
    FarmText_CNF2 = "Locations"
    FarmText_CNF3 = "Inspection"
    FarmText_CNF4 = "Sharing"
    FarmText_CNF5 = "Profile"
    FarmText_CNFB = "Filter"
    FarmText_CNF6 = "Mining filter options"
    FarmText_CNF7 = "Herbalism filter options"
    FarmText_CNF8 = "Fishing filter options"
    FarmText_CNF9 = "Treasure filter options"
    FarmText_CNFC = "Information"
    FarmText_CNF10 = "Help"
    FarmText_CNF11 = "Version"

    FarmText_CNF1H1 = "Worldmap tracking"
    FarmText_CNF1H2 = "Minimap tracking"
    FarmText_CNF1H3 = "Note"
    FarmText_CNF2H1 = "Worldmap options"
    FarmText_CNF2H2 = "Minimap options"
    FarmText_CNF3H1 = "Distant nodes"
    FarmText_CNF3H2 = "Nodes in sight"
    FarmText_CNF3H3 = "Anonymous nodes"
    FarmText_CNF3H4 = "Nodes after visit"
    FarmText_CNF4H1 = "Sharing with guild"
    FarmText_CNF4H2 = "Sharing with party/raid"
    FarmText_CNF4H3 = "Personal alert"
    FarmText_CNF4H4 = "Sharing blacklist"
    FarmText_CNF5H1 = "Select or delete a profile"
    FarmText_CNF5H2 = "Create or replace a profile"
    FarmText_CNF6H = "Mineral nodes to track"
    FarmText_CNF7H = "Herbal nodes to track"
    FarmText_CNF8H = "Fishing nodes to track"
    FarmText_CNF9H = "Treasure nodes to track"
    FarmText_CNF10H1 = "Chat commands"
    FarmText_CNF10H2 = "Key binding"
    FarmText_CNF11H1 = "Version"
    FarmText_CNF11H2 = "Introduction"
    FarmText_CNF11H3 = "Welcome message"

    FarmText_CNF1SON = "Show ore nodes"
    FarmText_CNF1SHN = "Show herb nodes"
    FarmText_CNF1STN = "Show treasure nodes"
    FarmText_CNF1SFN = "Show fish nodes"
    FarmText_CNF1MO = "Miners only"
    FarmText_CNF1HO = "Herbalists only"
    FarmText_CNF1TO = "Only if tracking"
    FarmText_CNF1A  = "All"
    FarmText_CNF1NT = "The \"All\" option causes the current filters for this category to be ignored and force all nodes to be shown."
    FarmText_CNF2DW = "Display nodes on worldmap"
    FarmText_CNF2DM = "Display nodes on minimap"
    FarmText_CNF2DT = "Display tooltips"
    FarmText_CNF2DB = "Display minimap button"
    FarmText_CNF2S1 = "Display: %d nodes"
    FarmText_CNF2S2 = "Opacity: %d%%"
    FarmText_CNF2S3 = "Icon size: %d"
    FarmText_CNF2S4 = "Range: %d y"
    FarmText_CNF2S5 = "Angle: %d°"
    FarmText_CNF2S6 = "Gap: %d"
    FarmText_CNF2O1 = "Display harvest counts"
    FarmText_CNF2O2 = "Display note source"
    FarmText_CNF2O3 = "Display last time"
    FarmText_CNF2O4 = "Display node distance"
    FarmText_CNF2O5 = "Display drop rates"
    FarmText_CNF3FO = "Fade out distant notes"
    FarmText_CNF3ET = "Regard tracking skill"
    FarmText_CNF3DA = "Display anonymous nodes"
    FarmText_CNF3MI = "Mark inspected nodes"
    FarmText_CNF3S1 = "Distance: %d y"
    FarmText_CNF3S2 = "Visibility: %d%%"
    FarmText_CNF3S3 = "Trackradius: %d y"
    FarmText_CNF3S4 = "Opacity: %d%%"
    FarmText_CNF3S5 = "Inspect at: %d y"
    FarmText_CNF3S6 = "Fading to: %d%%"
    FarmText_CNF3S7 = "Reappear: %d s"
    FarmText_CNF3O1 = "Replace by tracking icon when close"
    FarmText_CNF3O2 = "Only for active tracking skill"
    FarmText_CNF3O3 = "Tint anonymous nodes red"
    FarmText_CNF3O4 = "Tint close nodes green"
    FarmText_CNF4ES = "Enable synchronization"
    FarmText_CNF4PM = "Print a message when adding own find"
    FarmText_CNF4O1 = "Add received finds to my database"
    FarmText_CNF4O2 = "Print a message when sending a find"
    FarmText_CNF4O3 = "Print a message when receiving a find"
    FarmText_CNF5EXP = "Existing profiles:"
    FarmText_CNF5NPN = "New profile name:"

    FarmText_CLKL    = "|cffffff78Left click|r |cffffffff- Show/hide all nodes|r"
    FarmText_CLKLA   = "|cffffff78Left click + Shift/Ctrl/Alt|r |cffffffff- Show density report|r"
    FarmText_CLKR    = "|cffffff78Right click|r |cffffffff- Show farming report|r"
    FarmText_CLKRA   = "|cffffff78Right click + Shift/Ctrl/Alt|r |cffffffff- Show configuration window|r"

    FarmText_CNFVM   = "Installed addon version: IlarosFarm "
    FarmText_CNFLM   = "Installed language modules: deDE, enGB/enUS"
    FarmText_CNFGM   = "Supported game version: 3.3.5a (12340)"
    FarmText_CNFDM   = "IlarosFarm is developed by Tec's Ilaros WoW and corresponds to the content of this server. No warranty is given for functionality. The whole project is open source software and is licensed under the |cff00ff00GNU General Public License v3.0|r."
    FarmText_CNFSW   = "Show welcome message at start"

    -- Chat-Kommandos
    FarmText_ON      = "an"
    FarmText_OFF     = "aus"
    FarmText_SLASH   = "|cffff38ffIlarosFarm commands:|r"
    FarmText_COM     = "|cffffff78/Farm|r - overview of commands"
    FarmText_VER     = "|cffffff78/Farm v|r - version information"
    FarmText_OPT     = "|cffffff78/Farm k|r - show configuration window"
    FarmText_FRW     = "|cffffff78/Farm l|r - show farm report"
    FarmText_DRW     = "|cffffff78/Farm h|r - show density report"
    FarmText_MINI    = "|cffffff78/Farm m|r - show/hide nodes on minimap"
    FarmText_WRLD    = "|cffffff78/Farm w|r - show/hide nodes on worldmap"
    FarmText_CMDH    = "|cffffff78/Farm p|r - show/hide herbal nodes"
    FarmText_CMDM    = "|cffffff78/Farm e|r - show/hide mineral nodes"
    FarmText_CMDF    = "|cffffff78/Farm f|r - show/hide fishing nodes"
    FarmText_CMDT    = "|cffffff78/Farm s|r - show/hide treasure nodes"
    FarmText_MXD     = "|cffffff78/Farm dis <max>|r - show nodes up to <max> yards distance on minimap"
    FarmText_MXN     = "|cffffff78/Farm num <max>|r - show <max> nodes at most on minimap"

    FarmText_COMs    = "|cffffff78/Farm|r |cffffffff- overview of commands|r"
    FarmText_VERs    = "version information"
    FarmText_OPTs    = "show configuration window"
    FarmText_FRWs    = "show farm report"
    FarmText_DRWs    = "show density report"
    FarmText_MINIs   = "show/hide nodes on minimap"
    FarmText_WRLDs   = "show/hide nodes on worldmap"
    FarmText_CMDHs   = "show/hide herbal nodes"
    FarmText_CMDMs   = "show/hide mineral nodes"
    FarmText_CMDFs   = "show/hide fishing nodes"
    FarmText_CMDTs   = "show/hide treasure nodes"
    FarmText_MXDs    = "show nodes up to <max> yards distance on minimap"
    FarmText_MXNs    = "show <max> nodes at most on minimap"

    -- Tastaturbelegungsoptionen im Interface-Menü
    BINDING_HEADER_ILAROSFARM = "IlarosFarm"
    BINDING_NAME_ILAROSFARM_TOGGLE_OPTIONS_DIALOG = "Toggle configuration"
    FarmText_KBD     = "A key can be assigned to the configuration window of IlarosFarm by using the key binding menu."

    -- Knöpfe
    FarmText_BtnA = "Accept"
    FarmText_BtnI = "Ignore"
    FarmText_BtnO = "OK"
    FarmText_BtnY = "Yes"
    FarmText_BtnN = "No"
    FarmText_BtnC = "Cancel"
    FarmText_BtnK = "Options"
    FarmText_BtnS = "Search"
    FarmText_BtnD = "Delete"
    FarmText_BtnNP = "New"
    FarmText_BtnCP = "Copy"
    FarmText_BtnMS = "Mark selection"
    FarmText_BtnUS = "Unmark selection"
    FarmText_BtnUA = "Unmark all"
    FarmText_BtnSM = "Send marked"
    FarmText_BtnDM = "Delete marked"
    FarmText_BtnFS = "Fish school"

    -- Dialoge
    FarmText_DLG1  = "Add player to the blacklist"
    FarmText_DLG2  = "Do you wish to remove all nodes that have been shared by this player?"
    FarmText_DLG3  = "Are you sure? This can't be undone and will remove %d node(s)."
    FarmText_DLG4  = "%d node(s) have been permenently removed from database."
    FarmText_DLG5  = "Density Report"
    FarmText_DLG6  = "Farming Report"
    FarmText_DLG7  = "Do you wish to send %s node(s) to %s?\n|cffff0000The farming report window of the recipient must be open!|r"
    FarmText_DLG8  = "Do you wish to delete %s node(s)?"
    FarmText_DLG9  = "%s wants to send you %d farm nodes. Accept?"
    FarmText_DLG10 = "Do you wish to change %s nodes(s) to fish schools?\nCan only be used on fish that comes in schools. Additionally please mind the following conversion:\n\n|cffff0000Rumsey Rum Black Label|r\n>>>\n|cff00ff00Bloodsail Wreckage|r\n\n|cffff0000Watertight Trunk|r >>> |cff00ff00Schooner Wreckage|r\n\n|cffff0000Mote of Water|r >>> |cff00ff00Pure Water|r\n\n|cffff0000Iron Bound Trunk|r >>> |cff00ff00Waterlogged Wreckage|r\n\n|cffff0000Mithril Bound Trunk|r >>> |cff00ff00Floating Wreckage|r\n\n|cffff0000Tightly Sealed Trunk|r >>> |cff00ff00Floating Debris|r\n\n|cffff0000Elemental Water|r >>> |cff00ff00Patch of Elemental Water|r\n\n|cffff0000Steam Pump Debris|r >>> |cff00ff00Steam Pump Flotsam|r\n"

    -- Farmbericht
    FarmText_OPT1  = "Apply to Type"
    FarmText_OPT2  = "Apply to Region"
    FarmText_OPT3  = "Apply to Source"
    FarmText_LST1  = "Type"
    FarmText_LST2  = "Region"
    FarmText_LST3  = "Dist"
    FarmText_LST4  = "Source"
    FarmText_CMN   = "Marked nodes: "
    FarmText_STP   = "Player"
    FarmText_MRKN  = "Nodes will remain marked until they are unmarked, the user interface is reloaded, or the character logs out."
    FarmText_TLK1  = "Asking ..."
    FarmText_TLK2  = "Sending ..."
    FarmText_TLK3  = "Rejected!"
    FarmText_TLK4  = "Timed out."
    FarmText_TLK5  = "User busy."
    FarmText_TLK6  = "Finished."
    FarmText_TLK7  = "Success!"
    FarmText_TLK8  = "Received: "
    FarmText_TLK9  = "Finished: "
    FarmText_TLK10 = "Aborted at "
    FarmText_TLK11 = "Beginning ..."
    FarmText_TLK12 = "Upload aborted."
    FarmText_TLK13 = "Sent: "
    FarmText_UKNN  = "Unknown node: "

    -- Häufigkeitsbericht
    FarmText_sALL = "all"
    FarmText_cALL = "All"
    FarmText_LST5 = "Number"
    FarmText_LST6 = "Share %"

    -- Minikarte
    FarmText_MMH = "Hide Nodes"
    FarmText_MMS = "Show Nodes"

    -- Chat-Benachrichtigungen
    FarmText_Load = "IlarosFarm version %s loaded."

    FarmText_ADD  = "Added find of %s"
    FarmText_SND  = "Sent find of %s to %s"
    FarmText_RCV  = "Received find of %s in %s from %s (%s)"
    FarmText_RAID = "raid"
    FarmText_PRTY = "party"
    FarmText_GLD  = "guild"
    FarmText_WSP  = "whisper"
    FarmText_AND  = " and "

    FarmText_FName  = "|cffffff00IlarosFarm for Tec's Ilaros WoW|r"
    FarmText_FVer   = "|cffffff00Version %s|r"

    FarmText_SMini  = "|cffffff78IlarosFarm:|r |cff00ff00All nodes on minimap are shown.|r"
    FarmText_HMini  = "|cffffff78IlarosFarm:|r |cffff0000All nodes on minimap are hidden.|r"
    FarmText_SWorld = "|cffffff78IlarosFarm:|r |cff00ff00All nodes on worldmap are shown.|r"
    FarmText_HWorld = "|cffffff78IlarosFarm:|r |cffff0000All nodes on worldmap are hidden.|r"
    FarmText_NDist  = "|cffffff78IlarosFarm:|r |cff00ff00Displaying nodes up to %s y distance at most.|r"
    FarmText_NNumb  = "|cffffff78IlarosFarm:|r |cffff0000Displaying up to %s notes at once.|r"
    FarmText_STrad  = "|cffffff78IlarosFarm:|r |cff00ff00%s notes on minimap are shown.|r"
    FarmText_HTrad  = "|cffffff78IlarosFarm:|r |cffff0000%s notes on minimap are hidden.|r"

    -- Systemmeldungen
    FarmText_SYS1 = "WARNING!\nIlarosFarm has detected that your database version is invalid. Please press \"Accept\" to clear your database, or select \"Ignore\" if you want to try to repair your database manually."
    FarmText_SYS2 = "Your saved IlarosFarm database is too new. Your current database has been set aside until you upgrade IlarosFarm."
    FarmText_SYS3 = "IlarosFarm: Warnings"
    FarmText_SYS4 = "IlarosFarm was unable to identify the following zones: "..HIGHLIGHT_FONT_COLOR_CODE.."%s|r.\nIf these are new zones, then this is not a problem, and you can continue as normal.\nIf these are not new zones, "..HIGHLIGHT_FONT_COLOR_CODE.."your data IS NOT LOST!|r  But you will need to update IlarosFarm in order to access it. Until then you can continue as normal and any new data you collect will be merged with your old data once you upgrade.\n\n"..HIGHLIGHT_FONT_COLOR_CODE.."Please upgrade IlarosFarm as soon as possible.|r"
end
